---
name: Suggest Version Bump

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'database/**/*'

jobs:
  get-labels:
    uses: ./.github/workflows/get-pr-labels.yml

  suggest-bump:
    name: Suggest Version Bump
    needs: get-labels
    runs-on: ubuntu-latest
    steps:
      - name: Determine bump type
        id: bump
        run: |
          LABELS="${{ needs.get-labels.outputs.labels }}"
          BUMP="patch"
          echo "$LABELS" | grep -q 'type: feature' && BUMP="minor"
          echo "$LABELS" | grep -q 'type: security' && BUMP="minor"
          echo "$LABELS" | grep -q 'type: breaking' && BUMP="major"
          echo "bump=$BUMP" >> "$GITHUB_OUTPUT"

      - name: Report summary
        run: |
          echo "### 🚀 Suggested Version Bump: **${{ steps.bump.outputs.bump }}**" >> "$GITHUB_STEP_SUMMARY"
